#!/bin/sh
log "Starting S08-start..."
log "====================="


#=============================================
# 12.1) goto run stage, start YaST2 (firstboot)
#---------------------------------------------
disable_splash
log "\tStarting X11/VNC based session..."
#==================================================
# We are going to start a VNC or X11 based session
#--------------------------------------------------
if [ ! -z "$VNC" ] ; then
	vnc_message
fi
startYaST2

