#!/bin/sh
log "Starting S09-cleanup..."
log "======================="

#=============================================
# 13) second stage done, cleanup level
#---------------------------------------------
# 13.1) kill shell on second virtual console
if test ! -z "$SPID" ; then
	log "\tkill X-Server with PID: $SPID"
	kill -KILL $SPID >/dev/null 2>&1
fi
# 13.2) kill VNC server and remove VNC passwd
if [ ! -z "$VNC" ] ; then
	log "\tkill all VNC sessions..."
	killall Xvnc >/dev/null 2>&1
	rm -fv /root/.vnc/passwd
fi
# 13.3) stop network and sshd
if test ! -z "$Y2_NETWORK_ACTIVE" ; then
	log "\tShutdown SSH daemon and network interfaces..."
	test -z "$Y2_SSH_ACTIVE" && /usr/bin/systemctl stop sshd
        /usr/bin/systemctl stop network
fi

stop_unicode

if [ -e "/var/lib/YaST2/firstboot_reboot_after_finish" ] ; then
    log "\tRebooting system as requested by firstboot..."
    rm /var/lib/YaST2/firstboot_reboot_after_finish
    /sbin/reboot
fi

if [ -e "/var/lib/YaST2/firstboot_halt_after_finish" ] ; then
    log "\tHalting system as requested by firstboot..."
    rm /var/lib/YaST2/firstboot_halt_after_finish
    # Instead of calling halt directly we will rely on systemd
    # failed state, that is OnFailure=shutdown.target in the
    # YaST2-Firstboot.service (bsc#1095251)
    exit 1
fi
